# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: action

on: [push]
jobs:
  basic-on-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
 
      - name: Cypress tests
        run: npm run cy:run --record --key 89c1a6ea-f9c5-45fc-b0f0-85dc0d0a94a7
